// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mneogzfadfxxumgruqch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uZW9nemZhZGZ4eHVtZ3J1cWNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDMyNDIsImV4cCI6MjA2MDIxOTI0Mn0.gx6XvyL8cuG3cDF0LahyPZ7inonBSOym1LJm__ZkNJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);